version: '2'

services:
   vault:
     depends_on:
        - mysql
     image: vault
     ports:
       - 8200:8200
     environment:
       - VAULT_ADDR=http://127.0.0.1:8200
       - DB_HOST=mysql

     volumes:
       - ./hcl:/hcl
       - ./config:/config
     command: server -config=/config/config.hcl
     links:
       - mysql

   mysql:
     image: mysql
     environment:
       - MYSQL_ROOT_PASSWORD=verysecret
